repos:
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v20.1.8
  hooks:
  - id: clang-format
    files: ^(src|tests)/.*\.(c|h)$
    types: [file]
    args: ['-i']  # Apply changes in-place

- repo: https://github.com/pocc/pre-commit-hooks
  rev: v1.3.5
  hooks:
  - id: clang-tidy
    files: ^(src|tests)/.*\.(c|h)$
    args: ['-p=build', '--config-file=.clang-tidy']

