name: Build

on: [push, pull_request]

jobs:
  build:
    name: Building with ${{ matrix.compiler }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler: [clang, gcc]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
