name: Build

on: [push, pull_request]

jobs:
  build:
    name: Building with ${{ matrix.compiler }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler: [clang]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y rofi-dev
    - name: Set up Ruby 2.7 for the tests
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - uses: BSFishy/meson-build@v1.0.3
      with:
        action: test
        meson-version: 1.8.3
        ninja-version: 1.12.1
